/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "eu-west-1",
    aws_cognito_identity_pool_id:
      "eu-west-1:da1f03de-3e83-4811-9447-601c9649db9b",
    aws_cognito_region: "eu-west-1",
    aws_user_pools_id: "eu-west-1_XfLBtbDDM",
    aws_user_pools_web_client_id: "1roqo6ve2c7mcruhp42l48vd2t",
    oauth: {},
    aws_cognito_login_mechanism: ["PREFERRED_USERNAME"],
    aws_cognito_signup_attributes: ["EMAIL"],
    aws_cognito_mfa_configuration: "OFF",
    aws_cognito_mfa_types: ["SMS"],
    aws_cognito_password_protection_settings: {
      passwordPolicyMinLength: 8,
      passwordPolicyCharacters: [],
    },
    aws_appsync_graphqlEndpoint:
      "https://6ft3yqshsra55k6dthv33gubaq.appsync-api.eu-west-1.amazonaws.com/graphql",
    aws_appsync_region: "eu-west-1",
    aws_appsync_authenticationType: "API_KEY",
    aws_appsync_apiKey: "da2-6y7fiqgkd5f4dnpuicmjxsrsx4",
    aws_user_files_s3_bucket:
      "redditclonemain4bb3e661cb3d456fa6b06b69255b94e5215757-dev",
    aws_user_files_s3_bucket_region: "eu-west-1",
  };
  
  export default awsmobile;
  